apiVersion: apps/v1
kind: Deployment
metadata:
  name: html-env
spec:
  selector:
    matchLabels:
      env: Production
  replicas: 1
  template:
    metadata:
      labels:
        env: Production
    spec:
      containers:
      - name: html-prod
        image: vimal13/apache-webserver-php
        ports:
        - containerPort: 80
        volumeMounts:
          - name: pvc1
            mountPath: /var/www/html   
      volumes:
      - name: pvc1
        persistentVolumeClaim:
          claimName: pvc1
